Sounds = {
    ['Player_Ready_to_start'] = { [Languages.English] = "Player_Ready_to_start.mp3" },
    ['Player_Gwarek_First_attached'] = { [Languages.English] = "Player_Gwarek_First_attached.mp3" },
    ['Player_Gwarek_Second_attached'] = { [Languages.English] = "Player_Gwarek_Second_attached.mp3" },
    ['Player_Odra_attached'] = { [Languages.English] = "Player_Odra_attached.mp3" },
    ['Player_Polonia_ready'] = { [Languages.English] = "Player_Polonia_ready.mp3" },
    ['Player_TLK_Attached'] = { [Languages.English] = "Player_TLK_Attached.mp3" },
    
    ['MM_Gwarek_Start'] = { [Languages.English] = "MM_Gwarek_Start.mp3" },
    ['MM_Gwarek_First_attached'] = { [Languages.English] = "MM_Gwarek_First_attached.mp3" },
    ['MM_Gwarek_Tm502_20m'] = { [Languages.English] = "MM_Gwarek_Tm502_20m.mp3" },
    ['MM_Gwarek_Tm502_0m'] = { [Languages.English] = "MM_Gwarek_Tm502_0m.mp3" },
    ['MM_Gwarek_Tm502_Signal'] = { [Languages.English] = "MM_Gwarek_Tm502_Signal.mp3" },
    ['MM_Gwarek_Second_100m'] = { [Languages.English] = "MM_Gwarek_Second_100m.mp3" },
    ['MM_Gwarek_Second_30m'] = { [Languages.English] = "MM_Gwarek_Second_30m.mp3" },
    ['MM_Gwarek_Second_10m'] = { [Languages.English] = "MM_Gwarek_Second_10m.mp3" },
    ['MM_Gwarek_Second_5m'] = { [Languages.English] = "MM_Gwarek_Second_5m.mp3" },
    ['MM_Gwarek_Second_1m'] = { [Languages.English] = "MM_Gwarek_Second_1m.mp3" },
    ['MM_Gwarek_Second_attached'] = { [Languages.English] = "MM_Gwarek_Second_attached.mp3" },
    ['MM_Gwarek_In_place'] = { [Languages.English] = "MM_Gwarek_In_place.mp3" },
    ['MM_Gwarek_Done'] = { [Languages.English] = "MM_Gwarek_Done.mp3" },
    
    ['MM_Odra_Start'] = { [Languages.English] = "MM_Odra_Start.mp3" },
    
    ['MM_Polonia_Start'] = { [Languages.English] = "MM_Polonia_Start.mp3" },
    ['MM_Polonia_Tm29_20m'] = { [Languages.English] = "MM_Polonia_Tm29_20m.mp3" },
    ['MM_Polonia_Tm29_0m'] = { [Languages.English] = "MM_Polonia_Tm29_0m.mp3" },
    ['MM_Polonia_Tm29_Signal'] = { [Languages.English] = "MM_Polonia_Tm29_Signal.mp3" },
    ['MM_Polonia_100m'] = { [Languages.English] = "MM_Polonia_100m.mp3" },
    ['MM_Polonia_30m'] = { [Languages.English] = "MM_Polonia_30m.mp3" },
    ['MM_Polonia_10m'] = { [Languages.English] = "MM_Polonia_10m.mp3" },
    ['MM_Polonia_5m'] = { [Languages.English] = "MM_Polonia_5m.mp3" },
    ['MM_Polonia_1m'] = { [Languages.English] = "MM_Polonia_1m.mp3" },
    ['MM_Polonia_Bumped'] = { [Languages.English] = "MM_Polonia_Bumped.mp3" },
    ['MM_Polonia_Done'] = { [Languages.English] = "MM_Polonia_Done.mp3" },
    
    ['MM_TLK_Before_Tm1'] = { [Languages.English] = "MM_TLK_Before_Tm1.mp3" },
    ['MM_TLK_Tm1_0m'] = { [Languages.English] = "MM_TLK_Tm1_0m.mp3" },
    ['MM_TLK_Attached'] = { [Languages.English] = "MM_TLK_Attached.mp3" },
    ['MM_TLK_50m'] = { [Languages.English] = "MM_TLK_50m.mp3" },
    ['MM_TLK_Done'] = { [Languages.English] = "MM_TLK_Done.mp3" },
    
    ['MM_Ending_z231_0m'] = { [Languages.English] = "MM_Ending_z231_0m.mp3" },
    ['MM_Ending_Tm501_0m'] = { [Languages.English] = "MM_Ending_Tm501_0m.mp3" },
}